datadog/init.sls

requisites (at least now) should be in the form of `thing: name` not `thing.verb: name`

Fix requisites

---

datadog/init.sls

In preparation for HTTPS repo.
See https://github.com/DataDog/dd-agent/pull/1779

[apt] Add apt-transport-https to the deb install

---

datadog/init.sls

- Formula was not working for RedHat OS family; added for compatibility
- Used `os_family` for better compatibility between OS installations
- Datadog-agent package needs a repo refresh on first installed
- Formula was requiring HTTPS repo support (example: apt-transport-https on Debian based systems) without actually using HTTPS, so changed URLs to HTTPS
- Set `gpgcheck` to `1`, and added public gpgkey to formula for verification
- Set `sslverify` to `1` to verify the HTTPS endpoint
- Added `cpuarch` grain to be more compatible with Datadog's repo structure for RPM based installations
* Run a `salt '*' state.show_sls` to get proper highstate output
* Run a `salt '*' state.highstate test=True` on each environment before pushing changes
* Run a `salt-call cp.get_template salt://<file-uri> …

RedHat family compatibility and HTTPS by default

---

README.rst
datadog/files/check_type.yaml.jinja
datadog/files/datadog.conf.jinja
datadog/init.sls
pillar.example

This pull request is to add the ability configure all Datadog checks through Salt.
Since both Salt and Datadog use YAML for configuration, it's simple to essentially copy pillar data directly into Datadog check configuration files. This allows us to configure all Datadog checks through the Salt pillar which gives us the power to easily define different checks for different servers.

Configure checks

---

datadog/config.sls
datadog/service.sls

Make pillardata for checks optional. Allows for separation of different
checks for different roles/hosts.
Test by removing "checks:" from pillars.
Test by adding separate pillar file with:
```
datadog:
checks:
mycheck:
init_config:
instances:
- name: foo
```

Make datadog.checks optional

---

datadog/install.sls

the keyservers are a pool of sks servers with squid in front of them, we should probably retry on failures.

Retry on failure when pulling the gpg key from keyserver.ubuntu.com

---

datadog/install.sls

Use of short GPG key fingerprints should be avoided because of the high risk of collisions there is with those.
This replaces the short apt key fingerprint with the long one.

[install] Use long apt key fingerprint

---

datadog/config.sls
pillar.example
test/pillar/datadog.sls

Allow adding a `site` option in the pillar file to set the same option in the minions' `datadog.yaml` files.

Add site option

---

datadog/config.sls
pillar.example
test/pillar/datadog.sls

Allow adding a `python_version` option to choose which python version is loaded at runtime, since that option will be available in the Datadog Agent version 6.14.0.

Add python_version option

---

datadog/install.sls

In the near future, the Agent packages will be signed with
our newer GPG key. In preparation for this, the RHEL install
should import the new associated public key.

[install] Trust the new RPM GPG key on RHEL

---

datadog/config.sls
datadog/files/conf.yaml.jinja
datadog/files/datadog.conf.jinja
datadog/files/datadog.yaml.jinja
datadog/init.sls
datadog/install.sls
datadog/map.jinja
datadog/service.sls
datadog/uninstall.sls
pillar.example
test/pillar/datadog.sls

Separates the root pillar object `datadog` into two sub-objects:
- `config`, which describes the contents of the `datadog.yaml` config file that will be installed on the minions,
- `install_settings`, which contains various customisable parameters for the Agent install, such as the Agent version.
With this new structure, any arbitrary key can be put in `config`.
For now, what's in config is simply written in the `datadog.yaml` file, but making modifications before writing the file could also be possible in the future (if we want to check fields, for example).
Note: Agent 5 is using a .ini config file, and there's no ini renderer available easily, so we're using the old way with explicitly supported options (except a little cleaner: we're not matching regexes in a file we don't have …

[pillar] Revamp pillar file structure & allow arbitrary keys in datadog.yaml

---

datadog/config.sls
datadog/install.sls
datadog/map.jinja
datadog/service.sls
datadog/uninstall.sls

Removes the `pkg_name`, `service_name`, `config_folder` and `config_file` options, as they shouldn't be set by the user.
Removes the `checks_confd` option ; instead, uses the Agent `confd_path` option to get the location where checks configs are located.
Formula cleanup

Remove pillar variables not meant to be used

---

README.rst
datadog/config.sls
datadog/files/conf.yaml.jinja
pillar.example
test/pillar/datadog.sls

Adds a `version` option for each check configuration, allowing users to choose the check version used. Uses the `datadog-agent integration` command to get and install the chosen version.
Agent 6 only.
The check configuration has been moved under the `config` option of the check.
Support of the `datadog-agent integration` command.
Breaking change: check config is now in the `config` key of the check's section, instead of being directly in the check's section.
Previously, check configurations had this shape:
```
datadog:
checks:
<check_name>:
<check_config>
```
Now, they're defined this way:
```
datadog:
checks:
<check_name>:
config:
<check_config>
```

Add ability to choose integration version

---

datadog/config.sls

If Agent 6 is installed, puts the check config files in their respective `<check>.d` folder.
Check config files were put in the `conf.d` folder directly, which is the standard for Agent 5, but not Agent 6.

[Agent 6] Put check config in <check>.d directory

---

README.rst
datadog/config.sls
datadog/install.sls
datadog/map.jinja

Changes the formula to support the Agent v7 distribution channels (apt & yum repositories).
`latest` will now point to the latest package in the `7` channel.
Updates documentation to include v7.
Add support for the upcoming Agent v7.

Add Agent 7 support

---

datadog/install.sls
datadog/map.jinja

Fixes the yum repository path for beta installs (Agent 6 betas are in `beta/6`, Agent 7 betas in `beta/7`).
Fixes the regex which checks if a beta version will be installed (there was a `-[0-9]+` too much at the end of the regex). The previous regex would match `7.15.0~beta.1-1` and not `7.15.0~beta.1`, which makes the install fail since we add the `-1` again during the installation (giving `7.15.0~beta.1-1-1`, which is not an existing version).
Agent 7 testing.

Fix Agent 6 & 7 install from beta repositories

---

datadog/install.sls

Agent 7 packages will only be signed using our new GPG key, so we can remove the old one from the repository file if installing Agent 7.

[redhat] Only import latest GPG key when installing Agent 7

---

datadog/config.sls

Fixes the permissions of the `<check>.d` directory: `700` instead of `600`.

Fix checks config directory permissions

---

CHANGELOG.md
README.rst
datadog/config.sls
datadog/files/conf.yaml.jinja
datadog/files/datadog.conf.jinja
datadog/files/datadog.yaml.jinja
datadog/init.sls
datadog/install.sls
datadog/map.jinja
datadog/service.sls
datadog/uninstall.sls
pillar.example
test/pillar/datadog.sls
test/start.sh

Contains all PRs for the 3.0 release:
- Fix checks config directory permissions (#45)
- Testing nits (#44)
- Stop importing the old GPG key for the Agent 7 rpm package (#43)
- Fix Agent 6 & 7 install from beta repositories (#42)
- Agent 7 support (#40)
- Check config in `<check>.d` directory for Agent 6 and 7 (#39)
- Ability to choose check version (#37)
- Revamp pillar file structure, allow the use of any key in the datadog.yaml config for Agent 6 and 7 (#35)
- Unused variable cleanup (#36)

3.0 release

---

datadog/config.sls

Remove `conf.d/<check>.yaml` if a check is enabled and Agent 6/7 is installed, preventing config file duplication.
If the formula is run with <= 2.1 and then 3.0, then both `conf.d/<check>.yaml` and `conf.d/<check>.d/conf.yaml` are here, and the Agent picks up both config files, duplicating the checks.

Remove old check config file if check is installed with Agent 6/7

---

datadog/config.sls
datadog/files/install_info.jinja
datadog/map.jinja
test/utils/check_apt_install.py
test/utils/check_yum_install.py
test/utils/helpers.py

Creates `install_info` file with information about the install method used (overwrites any other existing file).
- The formula version is managed by git tags. I decided to hardcode the version in a variable because: (i) there is no guarantee that the user will clone the repo instead of, e. g., downloading the contents as a ZIP and (ii) there seems to be no way to run commands on the master (which is the one which could access this information anyway).
- The saltstack version provided by the `install_info` file is the one on the specific minion where it is being installed.
I added tests to the pipeline to check the install_info file is created with the correct information.

Create install info file

---

README.md

- Adds a checks section dedicated to logs
- Renames "integrations" section to checks as the Configuration intro section currently says `it contains three parts: config, install_settings, and checks.` and we're adding add't checks for logs.
Jira request for documentation

Addition of logs check section for docs

---

.circleci/config.yml
README.md
datadog/config.sls
test/pillar/datadog6.sls
test/pillar/datadog7.sls

Adds a `third_party` option to the checks config to specify that the check to install is a third-party check (defined in https://github.com/DataDog/integrations-extras).
Installing third-party integrations is supported since Agent 6.21.0/7.21.0.

 Allow installing third-party integrations

---

datadog/config.sls
datadog/service.sls

Only try to install integration if the targeted version is not already installed (to make the formula idempotent).
Watch integration installs: restart the datadog-agent service when at least one integration install happens.
Make formula idempotent.
Correctly restart the Agent on integration installs (it was only restarting on config file changes before).
The service watch list generation has become a bit heavy with all the added conditions, but they're necessary to make sure we don't try to match states that do not exist (which makes the formula fail).

Restart the datadog-agent service after an integration install

---

datadog/install.sls

Adds the new GPG keys for the apt and yum repos to the list of trusted keys.
Prepare future key rotation.

Trust new GPG keys

---

datadog/install.sls

The special DATADOG_RPM_KEY_CURRENT.public entry will always contain the key that is used to sign current metadata as well as newly released packages.

Add the 'CURRENT' public key entry, get keys from keys.datadoghq.com

---

datadog/install.sls

Enables `repo_gpgcheck` for yum repos (except Agent 5, where we don't sign repodata).
Enhanced security by verifying repodata signatures.
Ensure that packages of Agent 6/7 can still be installed on RH distros.

Enable repo_gpgcheck for Agent > 5 repos

---

datadog/install.sls
datadog/map.jinja

* By default, get keys from keys.datadoghq.com, not Ubuntu keyserver
* Always add the DATADOG_APT_KEY_CURRENT.public key (contains key used to sign current repodata)
* Add 'signed-by' option to all sources list lines
* On Debian >= 9 and Ubuntu >= 16, only add keys to /usr/share/keyrings/datadog-archive-keyring.gpg
* On older systems, also add the same keyring to /etc/apt/trusted.gpg.d

Implement improvements to APT keys management

---

datadog/install.sls
datadog/uninstall.sls

Installs the new datadog-signing-keys package.

Install datadog-signing-keys on Debian based platforms

---

CONTRIBUTING.md

Changes the default branch mentioned in the docs to `main`.
References to "salt master" are kept, as this is the name used by the SaltStack docs: https://docs.saltproject.io/en/latest/topics/salt_system_architecture.html#the-salt-system-architecture to refer to the instance (and systemctl service) that runs the commands on minion nodes.

Prepare master->main default branch switch

---

test/pillar/datadog.sls
test/pillar/datadog5.sls
test/pillar/datadog6.sls
test/pillar/datadog7.sls

[Since 7.40.0](https://github.com/DataDog/datadog-agent/issues/14152), specifying a valid hostname is mandatory to be able to install & run the Agent service in a container. This repository's CI tries to install the Agent in containers, which is why we now need to specify an explicit hostname.
Fix CI.
n/a
CI is green.

[CI] Fix CI by specifying hostname in containers

---

datadog/install.sls
datadog/map.jinja

Import a new future GPG key
WIth the 2024 GPG key rotation ongoing customer will need to start trusting a new future GPG key that will be used in 2028.

[2024 GPG Key Rotation] Import new GPG future key
