datadog/init.sls

Syntactic changes required for this formula to support salt 2015.5.0 (Lithium)
* Include Requisites Path from DaveDash
* Replace deprecated file.sed with file.replace

Changes for salt 2015.5.0 (Lithium)

---

datadog/init.sls

restart service if config file changes

watch config file for changes

---

datadog/install.sls

Trust the new APT Key

---

datadog/config.sls
datadog/defaults.yaml
datadog/init.sls
datadog/install.sls
datadog/map.jinja
datadog/service.sls
datadog/uninstall.sls

Make the formula a bit more idiomatic and make variable more flexible, preparing to support multiple version of the Datadog Agent.

cleanup and make config more flexible, preparing to support A6

---

README.rst

Fixes the code blocks issue in README.md

Fix code blocks in README

---

.circleci/config.yml
.gitignore
test/base/top_install.sls
test/base/top_uninstall.sls
test/dist/debian_Dockerfile
test/dist/redhat_Dockerfile
test/minion.d/masterless.conf
test/pillar/datadog5.sls
test/pillar/datadog6.sls
test/pillar/datadog7.sls
test/start.sh
test/utils/check_apt_install.py
test/utils/check_yum_install.py
test/utils/helpers.py
test/utils/systemctl.py

Fixes the provided Dockerfiles to make the mock systemctl work, allowing the formula to succeed in manual tests.
Adds CircleCI jobs to run the formula, on Ubuntu and CentOS, for Agent 5, 6 and 7, to check that it does work
Adds simple python checks to test that we end up in a correct state after a formula run (correct installation state + Agent major version).
Add a CI to make changes safer.

Add CircleCI

---

CHANGELOG.md

Release version 2.2 of the formula, with fixes to the check installation directory.

Release 2.2

---

CHANGELOG.md

Release version 3.1 of the formula.

Release 3.1

---

datadog/config.sls

Instead of making a direct comparison, use the built-in `to_bool` filter.
Better comparison.

Use to_bool filter instead of == true

---

CHANGELOG.md

Release version 3.2 of the formula.

Release 3.2

---

CHANGELOG.md
datadog/map.jinja

Release version 3.3 of the formula.

Release 3.3

---

README.md

Lint README to follow documentation [contributing](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md) guidelines
Docs hackday project
N/A
N/A

DOCS-2275 Lint README

---

CHANGELOG.md
datadog/map.jinja

Updates changelog & formula version.
Prepare 3.4 release.

Prepare 3.4 release

---

test/pillar/datadog6.sls
test/pillar/datadog7.sls

Fixes CI by updating bind9 version test-installed there.

Fix CI by updating used versions of packages to test-install

---

CHANGELOG.md
datadog/map.jinja

Changelog + version bump for version 3.5.

Release version 3.5

---

CHANGELOG.md

This PR adds a missing date in the changelog

Add missing date in the changelog

---

datadog/install.sls
datadog/map.jinja

Update signing method
Keys rotation
1. Test installation of signed package with current installation method (must fail)
2. Test installation of signed package with modified installation method

[AP-2105] Update signing keys

---

test/utils/systemctl.py

Update our systemctl docker shim to the latest version and ensure it waits for the PID file to be created when starting the service
Fixing the CI
The fix is minimal and is probably not correct enough to be upstreamed, but it is enough to fix our tests with agent >= 7.48

Update systemctl & ensure it waits for the pid file to be created

---

test/utils/check_apt_install.py
test/utils/check_yum_install.py
test/utils/systemctl.py

Lint python code

---

.circleci/config.yml
datadog/install.sls
datadog/map.jinja
test/utils/check_rpm_install.py

This PR allows the datadog-agent to be installed under SUSE Linux
https://datadoghq.atlassian.net/browse/APL-2293

Add support for SUSE

---

CHANGELOG.md
datadog/map.jinja

Release 3.7
